---
on: push

jobs:
  buildImage:
    name: Build Docker image
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - name: Build image
        run: docker build -t kindlegen .
